// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { extensionsId, type ExtensionsId } from './Extensions';
import { categoriesId, type CategoriesId } from './Categories';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';
import { z } from 'zod';

/** Represents the table public.extensions_to_categories */
export default interface ExtensionsToCategoriesTable {
  extensionId: ColumnType<ExtensionsId, ExtensionsId, ExtensionsId>;

  categoryId: ColumnType<CategoriesId, CategoriesId, CategoriesId>;
}

export type ExtensionsToCategories = Selectable<ExtensionsToCategoriesTable>;

export type NewExtensionsToCategories = Insertable<ExtensionsToCategoriesTable>;

export type ExtensionsToCategoriesUpdate = Updateable<ExtensionsToCategoriesTable>;

export const extensionsToCategories = z.object({
  extensionId: extensionsId,
  categoryId: categoriesId,
});

export const extensionsToCategoriesInitializer = z.object({
  extensionId: extensionsId,
  categoryId: categoriesId,
});

export const extensionsToCategoriesMutator = z.object({
  extensionId: extensionsId.optional(),
  categoryId: categoriesId.optional(),
});
