// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as CategoriesTable } from './Categories';
import type { default as ExtensionsTable } from './Extensions';
import type { default as ExtensionsToCategoriesTable } from './ExtensionsToCategories';

export default interface PublicSchema {
  categories: CategoriesTable;

  extensions: ExtensionsTable;

  extensionsToCategories: ExtensionsToCategoriesTable;
}
